### PR TITLE
Export renv (#55)

### PR DESCRIPTION
**Pull request by schochastics**
@chainsawriot not entirely sure yet if this is robust but it seems to be a minimal working version. I keep digging to make this more stable. Something I am wondering about is the git stuff for bioconductor. If you see other vulnerabilities, do let me know

### CODE REVIEW

**Comment by chainsawriot** [comment]
This is the generated json for an package. I think the brackets affect `renv`.

```json
    "Packages": {
        "slam": {
            "Package": [
                "slam"
            ],
            "Version": [
                "0.1-50"
            ],
            "Source": [
                "Repository"
            ],
            "Repository": [
                "CRAN"
            ]
        }
```

```r
> restore()

This project has not yet been activated.
Activating this project will ensure the project library is used during restore.
Please see `?renv::activate` for more details.

Would you like to activate this project before restore? [Y/n]: y
* Project '~/dev/misc/renvtest2' loaded. [renv 0.16.0]
* The project library is out of sync with the lockfile.
* Use `renv::restore()` to install packages recorded in the lockfile.
Error in vapply(x, f, ..., FUN.VALUE = character(1)) : 
  values must be type 'character',
 but FUN(X[[1]]) result is type 'list'
Traceback (most recent calls last):
6: restore()
5: renv_restore_report_actions(diff, current, lockfile)
4: renv_pretty_print_records_pair(lhs[names(lhs) %in% names(actions)], 
       rhs[names(rhs) %in% names(actions)], "The following package(s) will be updated:")
3: renv_pretty_print_records_pair_impl(old, new)
2: map_chr(all, function(package) {
       lhs <- old[[package]]
       rhs <- new[[package]]
       case(is.null(lhs$Source) ~ rhs$Repository %||% rhs$Source, 
           is.null(rhs$Source) ~ lhs$Repository %||% lhs$Source, 
           !is.null(rhs$Repository) ~ rhs$Repository, !is.null(rhs$Source) ~ 
               rhs$Source)
   })
1: vapply(x, f, ..., FUN.VALUE = character(1))
```

But I was wondering what the `resolve("renv")` does in the function?

**Comment by chainsawriot** [comment]
```r
pkg_list <- vector(mode = "list", length = 1)
pkg_list[[1]][["Package"]] <- "rtoot"
pkg_list[[1]][["Version"]] <- "0.1.0"
pkg_list[[1]][["Source"]] <- "Repository"
pkg_list[[1]][["Repository"]] <- "CRAN"
jsonlite::toJSON(pkg_list)
## [{"Package":["rtoot"],"Version":["0.1.0"],"Source":["Repository"],"Repository":["CRAN"]}] 
jsonlite::toJSON(pkg_list, auto_unbox = TRUE)
## [{"Package":"rtoot","Version":"0.1.0","Source":"Repository","Repository":"CRAN"}] 
```

**Comment by schochastics** [comment]
ah I forgot to include `auto_unbox` this should be fixed now. 

The `resolve("renv")` part I am actually not sure if this is needed like this. renv is also part of the renv lockfile so we could also kind of hard code it in?

**Comment by chainsawriot** [comment]
@schochastics Great! The smoke test is now working. (But it proves our point in the documentation, a lock file is not as great as a Dockerfile and rang.R. The restoration of the lock file generated by the example in the documentation doesn't work due to misconfigured `rJava`. And rJava is not working well with the approach renv uses. It's not an issue we can fix though.)

About the `resolve("renv")`, actually, it does nothing now and the smoke test still runs. And the issue is: if someone uses `renv::restore()` to rehydrate a lock file from someone else, `renv` should have been installed anyway.

**Comment by schochastics** [comment]
sounds awesome. Yeah having renv installed to rehydrate obviously makes sense. i will remove it

**Comment by schochastics** [comment]
@chainsawriot should be done now

**Comment by chainsawriot** [comment]
@schochastics Thanks a lot!

**Pull request merged**
