### PR TITLE
set snapshot date depending on pkgs (#53,#55)

### PR DESCRIPTION
**Pull request by schochastics**
@chainsawriot please check if you are ok with the logic of `.extract_date()`

### CODE REVIEW

**Comment by chainsawriot** [comment]
@schochastics "../testdata/bioc_renv.RDS" needs update.

**Comment by schochastics** [comment]
Yeah shouldnt have done this 5 minutes before dinner. Will fix later

**Comment by chainsawriot** [comment]
How about this: just use the original big `renv.lock` to test the parsing. And have a tiny `renv.lock` (with maybe 3 packages, one CRAN, one bioc, one GH) to do the integration test?

You can put different `renv.lock` files into directories.

**Comment by schochastics** [comment]
saw your comment to late but thats a good idea. Will implement that quickly

**Comment by schochastics** [comment]
@chainsawriot when these checks pass, then it is done

**Pull request merged**
