### PR TITLE
expose convert_edgelist (#56)

### PR DESCRIPTION
**Pull request by schochastics**
Turned it into a generic function that works with rang and ranglet objects.

### CODE REVIEW

**Comment by chainsawriot** [comment]
@schochastics If you prefer

```r
el <- do.call("rbind",lapply(x$ranglets,convert_edgelist))
```

can be replaced by 

```r
el <- vctrs::vec_rbind(lapply(x$ranglets,convert_edgelist))
```

now, probably slightly faster and more robust.

**Comment by schochastics** [comment]
ah nice will do that

**Comment by schochastics** [comment]
hmm that didnt work
 vctrs::vec_rbind doesnt seem to support a list of data frames as input?
@chainsawriot should I revert, or did I do something wrong?

**Comment by chainsawriot** [comment]
@schochastics Sorry, I checked and it doesn't work as I said. Please revert.

**Comment by schochastics** [comment]
@chainsawriot done. Happy that my faithful companion `do.call` for so many years remains useful

**Comment by chainsawriot** [comment]
Well

```r
### but need to import the triple bang
vctrs::vec_rbind(!!!(lapply(graph$ranglets, convert_edgelist)))
```

Rather than being smart like this, I rather opt for being familiar. Please keep the `do.call`.

**Comment by schochastics** [comment]
haha I was actually wondering if a series of "!" could solve this issue. Well, TIL

**Pull request merged**
