### PR TITLE
reduce dependencies (#94)

### PR DESCRIPTION
**Pull request by schochastics**
- [x] `gh`
- [x] `anytime`

`gh::gh` is now `.gh`

### CODE REVIEW

**Comment by schochastics** [comment]
@chainsawriot  do you want to get rid of `jsonlite` completely or just the one `jsonlite::read_json()` (which is gone now)?

**Comment by chainsawriot** [comment]
@schochastics I think we can keep `jsonlite` (and other instances of jsonlite) for now. Until we want to create those VCR tests.

https://github.com/chainsawriot/rang/blob/3d1b46eab460d5f28d93205c25741023dcda2eec/R/as_pkgrefs.R#L104

This needs to use `jsonlite` for offline reading.

**Comment by schochastics** [comment]
we can always go back to that simple json parser that was removed in https://github.com/chainsawriot/rang/commit/816777033752d2f0dc9390c51d9c6a99366e9e1e when we you want to switch to `vcr`

**Comment by schochastics** [comment]
ok gh and anytime are both gone. Could be merged if no other suggestions from you

**Comment by chainsawriot** [comment]
The missing codecov lines are not very important (we need to use Github Secret to get rid of it). I will merge it now. Thank you very much!

**Pull request merged**
